/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated"
import { Route as AuthenticatedIndexRouteImport } from "./routes/_authenticated/index"
import { Route as AuthenticatedWebTrafficRouteImport } from "./routes/_authenticated/web-traffic"
import { Route as AuthenticatedUsersRouteImport } from "./routes/_authenticated/users"
import { Route as AuthenticatedTiersRouteImport } from "./routes/_authenticated/tiers"
import { Route as AuthenticatedTicketsRouteImport } from "./routes/_authenticated/tickets"
import { Route as AuthenticatedRolesRouteImport } from "./routes/_authenticated/roles"
import { Route as AuthenticatedOrganizationsRouteImport } from "./routes/_authenticated/organizations"
import { Route as AuthenticatedMigrationsRouteImport } from "./routes/_authenticated/migrations"
import { Route as AuthenticatedMessagesRouteImport } from "./routes/_authenticated/messages"
import { Route as AuthenticatedFeatureRequestsRouteImport } from "./routes/_authenticated/feature-requests"
import { Route as AuthenticatedDataRouteImport } from "./routes/_authenticated/data"

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWebTrafficRoute = AuthenticatedWebTrafficRouteImport.update({
  id: "/web-traffic",
  path: "/web-traffic",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTiersRoute = AuthenticatedTiersRouteImport.update({
  id: "/tiers",
  path: "/tiers",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: "/tickets",
  path: "/tickets",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: "/roles",
  path: "/roles",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrganizationsRoute =
  AuthenticatedOrganizationsRouteImport.update({
    id: "/organizations",
    path: "/organizations",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMigrationsRoute = AuthenticatedMigrationsRouteImport.update({
  id: "/migrations",
  path: "/migrations",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: "/messages",
  path: "/messages",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeatureRequestsRoute =
  AuthenticatedFeatureRequestsRouteImport.update({
    id: "/feature-requests",
    path: "/feature-requests",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDataRoute = AuthenticatedDataRouteImport.update({
  id: "/data",
  path: "/data",
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof AuthenticatedIndexRoute
  "/login": typeof LoginRoute
  "/data": typeof AuthenticatedDataRoute
  "/feature-requests": typeof AuthenticatedFeatureRequestsRoute
  "/messages": typeof AuthenticatedMessagesRoute
  "/migrations": typeof AuthenticatedMigrationsRoute
  "/organizations": typeof AuthenticatedOrganizationsRoute
  "/roles": typeof AuthenticatedRolesRoute
  "/tickets": typeof AuthenticatedTicketsRoute
  "/tiers": typeof AuthenticatedTiersRoute
  "/users": typeof AuthenticatedUsersRoute
  "/web-traffic": typeof AuthenticatedWebTrafficRoute
}
export interface FileRoutesByTo {
  "/login": typeof LoginRoute
  "/data": typeof AuthenticatedDataRoute
  "/feature-requests": typeof AuthenticatedFeatureRequestsRoute
  "/messages": typeof AuthenticatedMessagesRoute
  "/migrations": typeof AuthenticatedMigrationsRoute
  "/organizations": typeof AuthenticatedOrganizationsRoute
  "/roles": typeof AuthenticatedRolesRoute
  "/tickets": typeof AuthenticatedTicketsRoute
  "/tiers": typeof AuthenticatedTiersRoute
  "/users": typeof AuthenticatedUsersRoute
  "/web-traffic": typeof AuthenticatedWebTrafficRoute
  "/": typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_authenticated": typeof AuthenticatedRouteWithChildren
  "/login": typeof LoginRoute
  "/_authenticated/data": typeof AuthenticatedDataRoute
  "/_authenticated/feature-requests": typeof AuthenticatedFeatureRequestsRoute
  "/_authenticated/messages": typeof AuthenticatedMessagesRoute
  "/_authenticated/migrations": typeof AuthenticatedMigrationsRoute
  "/_authenticated/organizations": typeof AuthenticatedOrganizationsRoute
  "/_authenticated/roles": typeof AuthenticatedRolesRoute
  "/_authenticated/tickets": typeof AuthenticatedTicketsRoute
  "/_authenticated/tiers": typeof AuthenticatedTiersRoute
  "/_authenticated/users": typeof AuthenticatedUsersRoute
  "/_authenticated/web-traffic": typeof AuthenticatedWebTrafficRoute
  "/_authenticated/": typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/data"
    | "/feature-requests"
    | "/messages"
    | "/migrations"
    | "/organizations"
    | "/roles"
    | "/tickets"
    | "/tiers"
    | "/users"
    | "/web-traffic"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/login"
    | "/data"
    | "/feature-requests"
    | "/messages"
    | "/migrations"
    | "/organizations"
    | "/roles"
    | "/tickets"
    | "/tiers"
    | "/users"
    | "/web-traffic"
    | "/"
  id:
    | "__root__"
    | "/_authenticated"
    | "/login"
    | "/_authenticated/data"
    | "/_authenticated/feature-requests"
    | "/_authenticated/messages"
    | "/_authenticated/migrations"
    | "/_authenticated/organizations"
    | "/_authenticated/roles"
    | "/_authenticated/tickets"
    | "/_authenticated/tiers"
    | "/_authenticated/users"
    | "/_authenticated/web-traffic"
    | "/_authenticated/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated": {
      id: "/_authenticated"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated/": {
      id: "/_authenticated/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/web-traffic": {
      id: "/_authenticated/web-traffic"
      path: "/web-traffic"
      fullPath: "/web-traffic"
      preLoaderRoute: typeof AuthenticatedWebTrafficRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/users": {
      id: "/_authenticated/users"
      path: "/users"
      fullPath: "/users"
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/tiers": {
      id: "/_authenticated/tiers"
      path: "/tiers"
      fullPath: "/tiers"
      preLoaderRoute: typeof AuthenticatedTiersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/tickets": {
      id: "/_authenticated/tickets"
      path: "/tickets"
      fullPath: "/tickets"
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/roles": {
      id: "/_authenticated/roles"
      path: "/roles"
      fullPath: "/roles"
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/organizations": {
      id: "/_authenticated/organizations"
      path: "/organizations"
      fullPath: "/organizations"
      preLoaderRoute: typeof AuthenticatedOrganizationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/migrations": {
      id: "/_authenticated/migrations"
      path: "/migrations"
      fullPath: "/migrations"
      preLoaderRoute: typeof AuthenticatedMigrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/messages": {
      id: "/_authenticated/messages"
      path: "/messages"
      fullPath: "/messages"
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/feature-requests": {
      id: "/_authenticated/feature-requests"
      path: "/feature-requests"
      fullPath: "/feature-requests"
      preLoaderRoute: typeof AuthenticatedFeatureRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/data": {
      id: "/_authenticated/data"
      path: "/data"
      fullPath: "/data"
      preLoaderRoute: typeof AuthenticatedDataRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDataRoute: typeof AuthenticatedDataRoute
  AuthenticatedFeatureRequestsRoute: typeof AuthenticatedFeatureRequestsRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedMigrationsRoute: typeof AuthenticatedMigrationsRoute
  AuthenticatedOrganizationsRoute: typeof AuthenticatedOrganizationsRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
  AuthenticatedTiersRoute: typeof AuthenticatedTiersRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWebTrafficRoute: typeof AuthenticatedWebTrafficRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDataRoute: AuthenticatedDataRoute,
  AuthenticatedFeatureRequestsRoute: AuthenticatedFeatureRequestsRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedMigrationsRoute: AuthenticatedMigrationsRoute,
  AuthenticatedOrganizationsRoute: AuthenticatedOrganizationsRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
  AuthenticatedTiersRoute: AuthenticatedTiersRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWebTrafficRoute: AuthenticatedWebTrafficRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
