import { v } from "convex/values";
import { mutation, query, internalMutation } from "./_generated/server";
import { Id } from "./_generated/dataModel";
import { createAuditLog } from "./auditHelpers";
import { checkBooleanFeature, checkNumericLimit } from "./featureRegistry";
import { rateLimiter } from "./rateLimits";

/**
 * Shared Secrets — Convex Mutations & Queries
 *
 * Provides secure, time-limited secret sharing with email-verified OTP access.
 * All secret values are client-encrypted (AES-256-GCM) before reaching the server.
 * The server never sees plaintext — only ciphertext encrypted by a key held
 * exclusively in the URL fragment.
 */

// ==========================================
// MUTATIONS
// ==========================================

/**
 * Create a new shared secret.
 * Called after the API route stores the encrypted payload in WorkOS Vault.
 *
 * Checks: auth, feature gate (secret_sharing + max_active_shares), rate limit.
 */
export const createShare = mutation({
  args: {
    token: v.string(),
    vaultRef: v.string(),
    variableId: v.id("environmentVariables"),
    variableKey: v.string(),
    organizationId: v.id("organizations"),
    projectId: v.id("projects"),
    userId: v.id("users"),
    mode: v.union(v.literal("one_time"), v.literal("time_limited")),
    expiresAt: v.number(),
    hasPassphrase: v.boolean(),
    recipientEmails: v.array(v.string()),
  },
  handler: async (ctx, args) => {
    const now = Date.now();

    // 1. Feature gate: secret_sharing boolean
    const boolGate = await checkBooleanFeature(
      ctx.db,
      args.organizationId,
      "secret_sharing"
    );
    if (!boolGate.allowed) {
      throw new Error(
        boolGate.reason ?? "Secret sharing is not enabled for your tier."
      );
    }

    // 2. Feature gate: max_active_shares numeric
    const activeCount = await countActiveShares(ctx.db, args.organizationId);
    const numGate = await checkNumericLimit(
      ctx.db,
      args.organizationId,
      "max_active_shares",
      activeCount
    );
    if (!numGate.allowed) {
      throw new Error(numGate.reason ?? "Active share limit reached.");
    }

    // 3. Rate limit
    await rateLimiter.limit(ctx, "shareCreate", {
      key: args.organizationId,
      throws: true,
    });

    // 4. Insert sharedSecrets record
    const shareId = await ctx.db.insert("sharedSecrets", {
      token: args.token,
      vaultRef: args.vaultRef,
      variableId: args.variableId,
      variableKey: args.variableKey,
      organizationId: args.organizationId,
      projectId: args.projectId,
      createdBy: args.userId,
      mode: args.mode,
      expiresAt: args.expiresAt,
      hasPassphrase: args.hasPassphrase,
      recipientEmails: args.recipientEmails.map((e) => e.toLowerCase().trim()),
      status: "active",
      totalViewCount: 0,
      createdAt: now,
    });

    // 5. Insert shareRecipients records
    for (const email of args.recipientEmails) {
      await ctx.db.insert("shareRecipients", {
        shareId,
        email: email.toLowerCase().trim(),
        otpAttempts: 0,
        otpVerified: false,
        hasViewed: false,
        createdAt: now,
      });
    }

    // 6. Audit log
    await createAuditLog(ctx, {
      organizationId: args.organizationId,
      projectId: args.projectId,
      variableId: args.variableId,
      userId: args.userId,
      action: "share.created",
      details: {
        variableKey: args.variableKey,
        mode: args.mode,
        recipientCount: args.recipientEmails.length,
        hasPassphrase: args.hasPassphrase,
        expiresAt: args.expiresAt,
      },
      involvesSensitiveData: true,
      resourceType: "security",
    });

    return { shareId };
  },
});

/**
 * Verify a recipient's email and generate an OTP.
 * Returns { success: true } regardless of whether the email matches
 * (to prevent email enumeration attacks).
 *
 * The actual OTP is returned separately so the API route can send it via email.
 * The hashed OTP is stored in shareRecipients.
 */
export const verifyRecipientEmail = mutation({
  args: {
    token: v.string(),
    email: v.string(),
    otpHash: v.string(), // SHA-256 hash of the 6-digit OTP (generated by API route)
  },
  handler: async (ctx, args) => {
    const now = Date.now();
    const email = args.email.toLowerCase().trim();

    // Rate limit
    await rateLimiter.limit(ctx, "shareVerifyEmail", {
      key: args.token,
      throws: true,
    });

    // Look up the share
    const share = await ctx.db
      .query("sharedSecrets")
      .withIndex("by_token", (q) => q.eq("token", args.token))
      .first();

    if (!share || share.status !== "active" || share.expiresAt < now) {
      // Return success anyway to not leak info
      return { success: true, emailMatched: false };
    }

    // Find the recipient record
    const recipient = await ctx.db
      .query("shareRecipients")
      .withIndex("by_share_and_email", (q) =>
        q.eq("shareId", share._id).eq("email", email)
      )
      .first();

    if (!recipient) {
      // Email doesn't match — return success anyway (anti-enumeration)
      return { success: true, emailMatched: false };
    }

    // Check if already locked out (5+ attempts and OTP hasn't expired yet)
    if (
      recipient.otpAttempts >= 5 &&
      recipient.otpExpiresAt &&
      recipient.otpExpiresAt >= now
    ) {
      return { success: true, emailMatched: false };
    }

    // Only reset attempts if previous OTP expired (natural timeout, not lockout bypass)
    const shouldResetAttempts =
      !recipient.otpExpiresAt || recipient.otpExpiresAt < now;

    // Store the hashed OTP with 5-minute TTL
    await ctx.db.patch(recipient._id, {
      otpCode: args.otpHash,
      otpExpiresAt: now + 5 * 60 * 1000, // 5 minutes
      otpAttempts: shouldResetAttempts ? 0 : recipient.otpAttempts,
    });

    // Audit log
    await createAuditLog(ctx, {
      organizationId: share.organizationId,
      projectId: share.projectId,
      variableId: share.variableId,
      userId: share.createdBy,
      action: "share.otp_sent",
      details: {
        variableKey: share.variableKey,
        recipientEmail: email,
      },
      involvesSensitiveData: true,
      resourceType: "security",
    });

    return { success: true, emailMatched: true };
  },
});

/**
 * Verify the OTP and claim the shared secret.
 * For one-time shares, atomically burns the share.
 *
 * Returns { vaultRef, hasPassphrase } on success so the API route
 * can read the ciphertext from Vault and return it to the client.
 */
export const verifyOtp = mutation({
  args: {
    token: v.string(),
    email: v.string(),
    otpHash: v.string(), // SHA-256 hash of the user-provided OTP
    ipAddress: v.optional(v.string()),
    userAgent: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const now = Date.now();
    const email = args.email.toLowerCase().trim();

    // Rate limit
    await rateLimiter.limit(ctx, "shareVerifyOtp", {
      key: args.token,
      throws: true,
    });

    // Look up the share
    const share = await ctx.db
      .query("sharedSecrets")
      .withIndex("by_token", (q) => q.eq("token", args.token))
      .first();

    if (!share) {
      throw new Error("Share not found.");
    }

    if (share.status === "burned") {
      throw new Error("This secret was already viewed and destroyed.");
    }

    if (share.status === "revoked") {
      throw new Error("This share link was revoked by the owner.");
    }

    if (share.status === "expired" || share.expiresAt < now) {
      throw new Error("This secret has expired.");
    }

    // Find the recipient
    const recipient = await ctx.db
      .query("shareRecipients")
      .withIndex("by_share_and_email", (q) =>
        q.eq("shareId", share._id).eq("email", email)
      )
      .first();

    if (!recipient) {
      throw new Error("Email not authorized for this share.");
    }

    // Check lockout
    if (recipient.otpAttempts >= 5) {
      throw new Error(
        "Too many failed attempts. This email has been locked out."
      );
    }

    // Check OTP exists and hasn't expired
    if (!recipient.otpCode || !recipient.otpExpiresAt) {
      throw new Error("No verification code found. Please request a new one.");
    }

    if (recipient.otpExpiresAt < now) {
      throw new Error(
        "Verification code has expired. Please request a new one."
      );
    }

    // Verify OTP hash
    if (recipient.otpCode !== args.otpHash) {
      // Increment attempts
      const newAttempts = recipient.otpAttempts + 1;
      await ctx.db.patch(recipient._id, {
        otpAttempts: newAttempts,
      });

      // Audit log failed attempt
      await createAuditLog(ctx, {
        organizationId: share.organizationId,
        projectId: share.projectId,
        variableId: share.variableId,
        userId: share.createdBy,
        action: "share.otp_failed",
        details: {
          variableKey: share.variableKey,
          recipientEmail: email,
          attemptsUsed: newAttempts,
          ipAddress: args.ipAddress,
        },
        involvesSensitiveData: true,
        resourceType: "security",
        ipAddress: args.ipAddress,
        userAgent: args.userAgent,
      });

      const remaining = 5 - newAttempts;
      throw new Error(
        remaining > 0
          ? `Invalid verification code. ${remaining} attempt${remaining === 1 ? "" : "s"} remaining.`
          : "Too many failed attempts. This email has been locked out."
      );
    }

    // OTP is valid! Mark recipient as verified and viewed
    await ctx.db.patch(recipient._id, {
      otpVerified: true,
      otpCode: undefined, // Clear the OTP
      otpExpiresAt: undefined,
      hasViewed: true,
      viewedAt: now,
      viewerIpAddress: args.ipAddress,
      viewerUserAgent: args.userAgent,
    });

    // For one-time shares, atomically burn
    if (share.mode === "one_time") {
      await ctx.db.patch(share._id, {
        status: "burned",
        burnedAt: now,
        totalViewCount: share.totalViewCount + 1,
      });

      // Audit: burned
      await createAuditLog(ctx, {
        organizationId: share.organizationId,
        projectId: share.projectId,
        variableId: share.variableId,
        userId: share.createdBy,
        action: "share.burned",
        details: {
          variableKey: share.variableKey,
          viewedByEmail: email,
          ipAddress: args.ipAddress,
        },
        involvesSensitiveData: true,
        resourceType: "security",
        ipAddress: args.ipAddress,
        userAgent: args.userAgent,
      });
    } else {
      // Time-limited: just increment view count
      await ctx.db.patch(share._id, {
        totalViewCount: share.totalViewCount + 1,
      });
    }

    // Audit: viewed
    await createAuditLog(ctx, {
      organizationId: share.organizationId,
      projectId: share.projectId,
      variableId: share.variableId,
      userId: share.createdBy,
      action: "share.viewed",
      details: {
        variableKey: share.variableKey,
        viewedByEmail: email,
        mode: share.mode,
        ipAddress: args.ipAddress,
      },
      involvesSensitiveData: true,
      resourceType: "security",
      ipAddress: args.ipAddress,
      userAgent: args.userAgent,
    });

    return {
      vaultRef: share.vaultRef,
      hasPassphrase: share.hasPassphrase,
      mode: share.mode,
    };
  },
});

/**
 * Revoke a shared secret. The creator, org admins, and team leads can revoke.
 */
export const revokeShare = mutation({
  args: {
    shareId: v.id("sharedSecrets"),
    userId: v.id("users"),
  },
  handler: async (ctx, args) => {
    const share = await ctx.db.get(args.shareId);
    if (!share) {
      throw new Error("Share not found.");
    }

    // Check if user is creator OR org admin/owner
    const isCreator = share.createdBy === args.userId;
    if (!isCreator) {
      const membership = await ctx.db
        .query("organizationMembers")
        .withIndex("by_org_and_user", (q) =>
          q.eq("organizationId", share.organizationId).eq("userId", args.userId)
        )
        .first();

      const isAdmin =
        membership?.role === "admin" || membership?.role === "team_lead";
      if (!isAdmin) {
        throw new Error("Not authorized to revoke this share.");
      }
    }

    if (share.status !== "active") {
      throw new Error(`Cannot revoke a share with status "${share.status}".`);
    }

    await ctx.db.patch(share._id, {
      status: "revoked",
      revokedAt: Date.now(),
      revokedBy: args.userId,
    });

    // Audit log
    await createAuditLog(ctx, {
      organizationId: share.organizationId,
      projectId: share.projectId,
      variableId: share.variableId,
      userId: args.userId,
      action: "share.revoked",
      details: {
        variableKey: share.variableKey,
        mode: share.mode,
      },
      involvesSensitiveData: true,
      resourceType: "security",
    });

    return { vaultRef: share.vaultRef };
  },
});

// ==========================================
// QUERIES
// ==========================================

/**
 * List shares for a specific variable, including recipient status.
 */
export const listByVariable = query({
  args: {
    variableId: v.id("environmentVariables"),
  },
  handler: async (ctx, args) => {
    const shares = await ctx.db
      .query("sharedSecrets")
      .withIndex("by_variable", (q) => q.eq("variableId", args.variableId))
      .collect();

    // Enrich with recipient data
    const result = await Promise.all(
      shares.map(async (share) => {
        const recipients = await ctx.db
          .query("shareRecipients")
          .withIndex("by_share", (q) => q.eq("shareId", share._id))
          .collect();

        return {
          ...share,
          recipients: recipients.map((r) => ({
            email: r.email,
            hasViewed: r.hasViewed,
            viewedAt: r.viewedAt,
            otpVerified: r.otpVerified,
          })),
        };
      })
    );

    return result;
  },
});

/**
 * List active shares across an organization (for dashboard widget).
 */
export const listActiveByOrg = query({
  args: {
    organizationId: v.id("organizations"),
  },
  handler: async (ctx, args) => {
    const shares = await ctx.db
      .query("sharedSecrets")
      .withIndex("by_organization", (q) =>
        q.eq("organizationId", args.organizationId)
      )
      .filter((q) => q.eq(q.field("status"), "active"))
      .collect();

    const result = await Promise.all(
      shares.map(async (share) => {
        const recipients = await ctx.db
          .query("shareRecipients")
          .withIndex("by_share", (q) => q.eq("shareId", share._id))
          .collect();

        return {
          _id: share._id,
          variableKey: share.variableKey,
          mode: share.mode,
          expiresAt: share.expiresAt,
          totalViewCount: share.totalViewCount,
          recipientCount: recipients.length,
          viewedCount: recipients.filter((r) => r.hasViewed).length,
          createdAt: share.createdAt,
          createdBy: share.createdBy,
        };
      })
    );

    return result;
  },
});

/**
 * List all shares for a specific project (all statuses), sorted by most recent.
 * Enriched with recipient data for admin/team-lead dashboards.
 */
export const listByProject = query({
  args: {
    projectId: v.id("projects"),
  },
  handler: async (ctx, args) => {
    const shares = await ctx.db
      .query("sharedSecrets")
      .withIndex("by_project", (q) => q.eq("projectId", args.projectId))
      .collect();

    // Sort by createdAt descending (most recent first)
    shares.sort((a, b) => b.createdAt - a.createdAt);

    // Enrich with recipient data
    const result = await Promise.all(
      shares.map(async (share) => {
        const recipients = await ctx.db
          .query("shareRecipients")
          .withIndex("by_share", (q) => q.eq("shareId", share._id))
          .collect();

        return {
          _id: share._id,
          variableKey: share.variableKey,
          mode: share.mode,
          status: share.status,
          expiresAt: share.expiresAt,
          hasPassphrase: share.hasPassphrase,
          totalViewCount: share.totalViewCount,
          createdAt: share.createdAt,
          createdBy: share.createdBy,
          recipients: recipients.map((r) => ({
            email: r.email,
            hasViewed: r.hasViewed,
            viewedAt: r.viewedAt,
            otpVerified: r.otpVerified,
          })),
        };
      })
    );

    return result;
  },
});

/**
 * Count active shares for an organization (for numeric limit check).
 */
export const countActiveByOrg = query({
  args: {
    organizationId: v.id("organizations"),
  },
  handler: async (ctx, args) => {
    const shares = await ctx.db
      .query("sharedSecrets")
      .withIndex("by_organization", (q) =>
        q.eq("organizationId", args.organizationId)
      )
      .filter((q) => q.eq(q.field("status"), "active"))
      .collect();
    return shares.length;
  },
});

// ==========================================
// INTERNAL HELPERS
// ==========================================

async function countActiveShares(
  db: any,
  organizationId: Id<"organizations">
): Promise<number> {
  const shares = await db
    .query("sharedSecrets")
    .withIndex("by_organization", (q: any) =>
      q.eq("organizationId", organizationId)
    )
    .filter((q: any) => q.eq(q.field("status"), "active"))
    .collect();
  return shares.length;
}

// ==========================================
// CRON HANDLERS (Internal Mutations)
// ==========================================

/**
 * Clean up expired shared secrets.
 * Transitions active shares past their expiresAt to "expired" status.
 */
export const cleanupExpiredShares = internalMutation({
  handler: async (ctx) => {
    const now = Date.now();

    // Find active shares that have expired
    const expired = await ctx.db
      .query("sharedSecrets")
      .withIndex("by_status_and_expires", (q) =>
        q.eq("status", "active").lt("expiresAt", now)
      )
      .collect();

    let count = 0;
    for (const share of expired) {
      await ctx.db.patch(share._id, {
        status: "expired",
      });

      // Audit log
      await createAuditLog(ctx, {
        organizationId: share.organizationId,
        projectId: share.projectId,
        variableId: share.variableId,
        userId: share.createdBy,
        action: "share.expired",
        details: {
          variableKey: share.variableKey,
          mode: share.mode,
          expiresAt: share.expiresAt,
        },
        involvesSensitiveData: true,
        resourceType: "security",
      });

      count++;
    }

    return { expired: count };
  },
});

/**
 * Clean up expired OTP codes from share recipients.
 * Clears OTP fields where the TTL has passed.
 */
export const cleanupExpiredOtps = internalMutation({
  handler: async (ctx) => {
    const now = Date.now();

    // Get all share recipients that have an OTP set
    // We need to scan since we don't have an index on otpExpiresAt
    const allRecipients = await ctx.db.query("shareRecipients").collect();

    let cleaned = 0;
    for (const recipient of allRecipients) {
      if (
        recipient.otpCode &&
        recipient.otpExpiresAt &&
        recipient.otpExpiresAt < now
      ) {
        await ctx.db.patch(recipient._id, {
          otpCode: undefined,
          otpExpiresAt: undefined,
        });
        cleaned++;
      }
    }

    return { cleaned };
  },
});
